name = "ElectroMechanicsFEM"
uuid = "3e3237d9-63df-4510-8634-5aa762e77746"
version = "0.1.0"
authors = ["Patricio Farrell", "Yiannis Hadjimichael", "Christian Merdon"]

[deps]
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ExtendableFEM = "a722555e-65e0-4074-a036-ca7ce79a4aed"
ExtendableFEMBase = "12fb9182-3d4c-4424-8fd1-727a0899810c"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
ExtendableSparse = "95c220a8-a1cf-11e9-0c77-dbfce5f500b3"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GridVisualize = "5eed8a63-0fb0-45eb-886d-8d5a387d12b8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SimplexGridFactory = "57bfcd06-606e-45d6-baf4-4ba06da0efd5"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
TetGen = "c5d3f3f7-f850-59f6-8a2e-ffc6dc1317ea"
Triangulate = "f7e6ffb2-c36d-4f8f-a77e-16e897189344"

[compat]
Aqua = "0.8"
DataFrames = "1.8.1"
DiffResults = "1.1.0"
DocStringExtensions = "0.9.5"
DrWatson = "2.19.1"
ExplicitImports = "1"
ExtendableFEM = "1.1.1"
ExtendableFEMBase = "1.1.0"
ExtendableGrids = "1.13.1"
ExtendableSparse = "1,2"
ForwardDiff = "1.3.1"
GridVisualize = "1.9.0"
LinearAlgebra = "1.9.0"
LinearSolve = "3"
Metis = "1.5.0"
Pardiso = "1.1.2"
Printf = "1.9.0"
SimplexGridFactory = "2.4"
SparseArrays = "1.9.0"
SparseDiffTools = "2.26.0"
Test = "1.9"
TetGen = "2.0"
Triangulate = "2.4"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
Pardiso = "46dd5b70-b6fb-5a00-ae2d-e8fea33afaf2"

[targets]
test = ["Aqua", "ExplicitImports", "Test", "DrWatson", "DataFrames", "Metis", "Pardiso"]
